// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanA.Context;

#nullable disable

namespace PlanA.Migrations
{
    [DbContext(typeof(PlanADbContext))]
    [Migration("20251110091408_operItemType")]
    partial class operItemType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ItemOperation", b =>
                {
                    b.Property<int>("ItemsItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationsOperationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsItemId", "OperationsOperationId");

                    b.HasIndex("OperationsOperationId");

                    b.ToTable("ItemOperation");
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.Property<int>("ItemsItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsItemId", "OrdersOrderId");

                    b.HasIndex("OrdersOrderId");

                    b.ToTable("ItemOrder");
                });

            modelBuilder.Entity("PlanA.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemId1");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PlanA.Models.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationId");

                    b.HasIndex("ProcessId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("PlanA.Models.Operation_items", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "OperationId");

                    b.HasIndex("OperationId");

                    b.ToTable("Operation_Items", (string)null);
                });

            modelBuilder.Entity("PlanA.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PlanA.Models.Order_items", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("Order_Items", (string)null);
                });

            modelBuilder.Entity("PlanA.Models.Process", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcessId");

                    b.HasIndex("ProcessId1");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("PlanA.Models.Sub_items", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "SubItemId");

                    b.HasIndex("SubItemId");

                    b.ToTable("Sub_Items", (string)null);
                });

            modelBuilder.Entity("PlanA.Models.Sub_process", b =>
                {
                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubProcessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcessId", "SubProcessId");

                    b.HasIndex("SubProcessId");

                    b.ToTable("Sub_Processes", (string)null);
                });

            modelBuilder.Entity("ItemOperation", b =>
                {
                    b.HasOne("PlanA.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Operation", null)
                        .WithMany()
                        .HasForeignKey("OperationsOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.HasOne("PlanA.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlanA.Models.Item", b =>
                {
                    b.HasOne("PlanA.Models.Item", null)
                        .WithMany("SubItems")
                        .HasForeignKey("ItemId1");
                });

            modelBuilder.Entity("PlanA.Models.Operation", b =>
                {
                    b.HasOne("PlanA.Models.Process", null)
                        .WithMany("Operations")
                        .HasForeignKey("ProcessId");
                });

            modelBuilder.Entity("PlanA.Models.Operation_items", b =>
                {
                    b.HasOne("PlanA.Models.Item", "Item")
                        .WithMany("OperationItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Operation", "Operation")
                        .WithMany("OperationItems")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("PlanA.Models.Order_items", b =>
                {
                    b.HasOne("PlanA.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PlanA.Models.Process", b =>
                {
                    b.HasOne("PlanA.Models.Process", null)
                        .WithMany("SubProcesses")
                        .HasForeignKey("ProcessId1");
                });

            modelBuilder.Entity("PlanA.Models.Sub_items", b =>
                {
                    b.HasOne("PlanA.Models.Item", "Item")
                        .WithMany("ItemSubitems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Item", "SubItem")
                        .WithMany()
                        .HasForeignKey("SubItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SubItem");
                });

            modelBuilder.Entity("PlanA.Models.Sub_process", b =>
                {
                    b.HasOne("PlanA.Models.Process", "Process")
                        .WithMany("ItemSubProcesses")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Process", "SubProcess")
                        .WithMany()
                        .HasForeignKey("SubProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("SubProcess");
                });

            modelBuilder.Entity("PlanA.Models.Item", b =>
                {
                    b.Navigation("ItemSubitems");

                    b.Navigation("OperationItems");

                    b.Navigation("OrderItems");

                    b.Navigation("SubItems");
                });

            modelBuilder.Entity("PlanA.Models.Operation", b =>
                {
                    b.Navigation("OperationItems");
                });

            modelBuilder.Entity("PlanA.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PlanA.Models.Process", b =>
                {
                    b.Navigation("ItemSubProcesses");

                    b.Navigation("Operations");

                    b.Navigation("SubProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
