// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanA.Context;

#nullable disable

namespace PlanA.Migrations
{
    [DbContext(typeof(PlanADbContext))]
    [Migration("20260216090451_empl+eqip")]
    partial class empleqip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EmployeeEquipment", b =>
                {
                    b.Property<int>("EmployeesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeesId", "EquipmentsId");

                    b.HasIndex("EquipmentsId");

                    b.ToTable("EmployeeEquipment");
                });

            modelBuilder.Entity("ItemOperation", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsId", "OperationsId");

                    b.HasIndex("OperationsId");

                    b.ToTable("ItemOperation");
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("ItemOrder");
                });

            modelBuilder.Entity("OperationProcess", b =>
                {
                    b.Property<int>("OperationsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationsId", "ProcessesId");

                    b.HasIndex("ProcessesId");

                    b.ToTable("OperationProcess");
                });

            modelBuilder.Entity("PlanA.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("PlanA.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Salary")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PlanA.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("PlanA.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("PlanA.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("PlanA.Models.Operation_items", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "OperationId");

                    b.HasIndex("OperationId");

                    b.ToTable("Operation_Items", (string)null);
                });

            modelBuilder.Entity("PlanA.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualDateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualDateStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanDateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanDateStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PlanA.Models.Order_items", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("Order_Items", (string)null);
                });

            modelBuilder.Entity("PlanA.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PlanA.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("PlanA.Models.Sub_items", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "SubItemId");

                    b.HasIndex("SubItemId");

                    b.ToTable("Sub_Items", (string)null);
                });

            modelBuilder.Entity("PlanA.Models.Sub_process", b =>
                {
                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubProcessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcessId", "SubProcessId");

                    b.HasIndex("SubProcessId");

                    b.ToTable("Sub_Processes", (string)null);
                });

            modelBuilder.Entity("EmployeeEquipment", b =>
                {
                    b.HasOne("PlanA.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemOperation", b =>
                {
                    b.HasOne("PlanA.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Operation", null)
                        .WithMany()
                        .HasForeignKey("OperationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.HasOne("PlanA.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OperationProcess", b =>
                {
                    b.HasOne("PlanA.Models.Operation", null)
                        .WithMany()
                        .HasForeignKey("OperationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Process", null)
                        .WithMany()
                        .HasForeignKey("ProcessesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlanA.Models.Employee", b =>
                {
                    b.HasOne("PlanA.Models.Person", "Person")
                        .WithMany("Employees")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PlanA.Models.Item", b =>
                {
                    b.HasOne("PlanA.Models.Asset", "Asset")
                        .WithOne("Item")
                        .HasForeignKey("PlanA.Models.Item", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Item", null)
                        .WithMany("SubItems")
                        .HasForeignKey("ItemId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PlanA.Models.Operation_items", b =>
                {
                    b.HasOne("PlanA.Models.Item", "Item")
                        .WithMany("OperationItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Operation", "Operation")
                        .WithMany("OperationItems")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("PlanA.Models.Order_items", b =>
                {
                    b.HasOne("PlanA.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PlanA.Models.Process", b =>
                {
                    b.HasOne("PlanA.Models.Process", null)
                        .WithMany("SubProcesses")
                        .HasForeignKey("ProcessId");
                });

            modelBuilder.Entity("PlanA.Models.Sub_items", b =>
                {
                    b.HasOne("PlanA.Models.Item", "Item")
                        .WithMany("ItemSubitems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Item", "SubItem")
                        .WithMany()
                        .HasForeignKey("SubItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SubItem");
                });

            modelBuilder.Entity("PlanA.Models.Sub_process", b =>
                {
                    b.HasOne("PlanA.Models.Process", "Process")
                        .WithMany("ItemSubProcesses")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanA.Models.Process", "SubProcess")
                        .WithMany()
                        .HasForeignKey("SubProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("SubProcess");
                });

            modelBuilder.Entity("PlanA.Models.Asset", b =>
                {
                    b.Navigation("Item");
                });

            modelBuilder.Entity("PlanA.Models.Item", b =>
                {
                    b.Navigation("ItemSubitems");

                    b.Navigation("OperationItems");

                    b.Navigation("OrderItems");

                    b.Navigation("SubItems");
                });

            modelBuilder.Entity("PlanA.Models.Operation", b =>
                {
                    b.Navigation("OperationItems");
                });

            modelBuilder.Entity("PlanA.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PlanA.Models.Person", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PlanA.Models.Process", b =>
                {
                    b.Navigation("ItemSubProcesses");

                    b.Navigation("SubProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
